In [73]:
import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import StandardScaler

In [74]:
continuous_features = ['latDev', 'longDev', 'elevSat', 'loraTP', 'loraSF', 'doppler', 'alt', 'raan', 'srcId']
cols_to_drop        = ['dstId', 'srcSat', 'dstSat', 'loraCF', 'loraBW', 'loraCR', 'satId'] #, 'srcId']

-------> Processing Seed 1/10 ---
-------> Processing Seed 2/10 ---
-------> Processing Seed 3/10 ---
-------> Processing Seed 4/10 ---
-------> Processing Seed 5/10 ---
-------> Processing Seed 6/10 ---
-------> Processing Seed 7/10 ---
-------> Processing Seed 8/10 ---
-------> Processing Seed 9/10 ---
-------> Processing Seed 10/10 ---

In [77]:
def create_sequences_data(df, scaler, seq_length):    
    df = df.drop(columns=cols_to_drop)

    # Sort by id_simulaiton and time
    df = df.sort_values(by=['id_simulation', 'srcId','time']).reset_index(drop=True)
    
    # Apply StandardScaler         
    #df[continuous_features] = scaler.transform(df[continuous_features])

    # Process data
    seq_X   = []
    label_y = []
    for sim_id, group_df in df.groupby(by=['id_simulation', 'srcId']):        
        num_features_array  = group_df[continuous_features].values
        time_array          = group_df['time'].values
        target_array        = group_df['rcvOk'].values
        num_packets         = len(group_df)
        
        # Discard if the simulation has less than SEQ_LENGHTS
        if num_packets < seq_length:
            continue
                    
        # Create sliding windows - Ventanas deslizantes
        for i in range(num_packets - seq_length + 1):
            # Select the window        
            window_num      = num_features_array[i : i + seq_length]
            ###window_cat      = cat_features_array[i : i + SEQ_LENGTH].reshape(-1, 1)
            window_times    = time_array[i : i + seq_length]
            window_targets  = target_array[i : i + seq_length]
            
            # El paquete central a predecir es el último de la ventana
            # The prediction should be the last elemento of the window
            target_idx      = seq_length - 1
            label_target    = window_targets[target_idx]
            time_target     = window_times[target_idx]
                        
            # Si un paquete ocurrió en el mismo segundo que el objetivo, delta_t = 0        
            #delta_t = (window_times - time_target).reshape(-1, 1)
            delta_t = (time_target - window_times).reshape(-1, 1)
            #delta_t =  time_target - window_times
            #print('delta_t: ', delta_t)
            
            #window_X = np.hstack((window_num, window_cat, delta_t))
            window_X = np.hstack((window_num, delta_t))

            seq_X.append(window_X)
            label_y.append(label_target)
    #print("seq_X: ", len(seq_X), "label_y: ", len(label_y))
    #print(seq_X)
    return seq_X, label_y
    #X = torch.tensor(np.array(seq_X), dtype=torch.float32)
    #y = torch.tensor(np.array(label_y), dtype=torch.float32)

In [118]:
(77.62/22.38) ** 0.5

1.8623305951831266

In [78]:
base_path  = 'data/repetitions/'
num_seeds  = 10
for seed in range(num_seeds):
    print(f"-------> Processing Seed {seed+1}/{num_seeds} ---")

    # Construcción dinámica de nombres de archivos
    path_train = os.path.join(base_path, f'seed_{seed}_final_train_data_transmission.csv')
    path_test  = os.path.join(base_path, f'seed_{seed}_final_test_data_transmission.csv')
    path_val   = os.path.join(base_path, f'seed_{seed}_final_val_data_transmission.csv')

    df_train = pd.read_csv(path_train)
    df_test  = pd.read_csv(path_test)
    df_val   = pd.read_csv(path_val)

    X_train_features = df_train[continuous_features].values
    X_test_features = df_test[continuous_features].values
    X_val_features = df_val[continuous_features].values


    scaler = StandardScaler()
    scaler.fit(X_train_features)
    
    seq_length = 8
    #X_train, y_train = 
    seq_X, label_y = create_sequences_data(df_train, scaler, seq_length)
    #X_test , y_test  = create_sequences_data(df_test, scaler, seq_length)
    #X_val  , y_val   = create_sequences_data(df_val, scaler, seq_length)

-------> Processing Seed 1/10 ---
-------> Processing Seed 2/10 ---
-------> Processing Seed 3/10 ---
-------> Processing Seed 4/10 ---
-------> Processing Seed 5/10 ---
-------> Processing Seed 6/10 ---
-------> Processing Seed 7/10 ---
-------> Processing Seed 8/10 ---
-------> Processing Seed 9/10 ---
-------> Processing Seed 10/10 ---

In [79]:
print(len(seq_X))
seq_X[4]

43680

array([[ 5.280190e+01, -1.403250e-01,  3.420890e+00,  1.995300e-02,
         1.200000e+01,  1.822140e+04,  6.000000e+02,  1.700000e+02,
         0.000000e+00,  1.147922e+02],
       [ 5.280190e+01, -1.403250e-01,  4.377740e+00,  1.995300e-02,
         1.200000e+01,  1.808060e+04,  6.000000e+02,  1.700000e+02,
         0.000000e+00,  1.003004e+02],
       [ 5.280190e+01, -1.403250e-01,  5.540480e+00,  1.995300e-02,
         1.200000e+01,  1.785030e+04,  6.000000e+02,  1.700000e+02,
         0.000000e+00,  8.331200e+01],
       [ 5.280190e+01, -1.403250e-01,  7.244680e+00,  1.995300e-02,
         1.200000e+01,  1.738470e+04,  6.000000e+02,  1.700000e+02,
         0.000000e+00,  5.958700e+01],
       [ 5.280190e+01, -1.403250e-01,  8.264760e+00,  1.995300e-02,
         1.200000e+01,  1.714830e+04,  6.000000e+02,  1.700000e+02,
         0.000000e+00,  4.601500e+01],
       [ 5.280190e+01, -1.403250e-01,  9.126840e+00,  1.995300e-02,
         1.200000e+01,  1.677860e+04,  6.000000e+02,  1.700000e+02,
         0.000000e+00,  3.488800e+01],
       [ 5.280190e+01, -1.403250e-01,  1.074480e+01,  1.995300e-02,
         1.200000e+01,  1.621290e+04,  6.000000e+02,  1.700000e+02,
         0.000000e+00,  1.478800e+01],
       [ 5.280190e+01, -1.403250e-01,  1.198520e+01,  1.995300e-02,
         1.200000e+01,  1.577300e+04,  6.000000e+02,  1.700000e+02,
         0.000000e+00,  0.000000e+00]])

In [114]:
print(len(seq_X))
#
print(np.array2string(seq_X[52], suppress_small=True))

43680
[[    52.8019       -0.140325     -8.44096       0.019953     12.
  -19339.6         600.          170.            0.          127.669   ]
 [    52.8019       -0.140325     -9.38489       0.019953     12.
  -19347.3         600.          170.            0.          107.073   ]
 [    52.8019       -0.140325     -9.95082       0.019953     12.
  -19267.6         600.          170.            0.           94.524   ]
 [    52.8019       -0.140325    -10.5471        0.019953     12.
  -19190.          600.          170.            0.           81.145   ]
 [    52.8019       -0.140325    -11.1193        0.019953     12.
  -19314.2         600.          170.            0.           68.155   ]
 [    52.8019       -0.140325    -12.0168        0.019953     12.
  -19297.3         600.          170.            0.           47.494   ]
 [    52.8019       -0.140325    -13.0784        0.019953     12.
  -19094.6         600.          170.            0.           22.62    ]
 [    52.8019       -0.140325    -14.0275        0.019953     12.
  -19077.8         600.          170.            0.            0.      ]]

In [117]:
aux_df = df_train.sort_values(by=['id_simulation', 'srcId','time']).reset_index(drop=True)
aux_df[(aux_df['srcId'] == 0) & (aux_df['id_simulation'] == 'sim_alt_600_raan_170')][['latDev', 'longDev', 'elevSat', 'loraTP', 'loraSF', 'doppler', 'alt', 'raan', 'srcId']].tail(8)
#aux_df.head()

     latDev   longDev   elevSat    loraTP  loraSF  doppler  alt  raan  srcId
52  52.8019 -0.140325  -8.44096  0.019953      12 -19339.6  600   170      0
53  52.8019 -0.140325  -9.38489  0.019953      12 -19347.3  600   170      0
54  52.8019 -0.140325  -9.95082  0.019953      12 -19267.6  600   170      0
55  52.8019 -0.140325 -10.54710  0.019953      12 -19190.0  600   170      0
56  52.8019 -0.140325 -11.11930  0.019953      12 -19314.2  600   170      0
57  52.8019 -0.140325 -12.01680  0.019953      12 -19297.3  600   170      0
58  52.8019 -0.140325 -13.07840  0.019953      12 -19094.6  600   170      0
59  52.8019 -0.140325 -14.02750  0.019953      12 -19077.8  600   170      0

In [64]:
aux_df = df_train.groupby(by=['srcId']).size().reset_index(name='counts')
aux_df

    srcId  counts
0       0     120
1       1     120
2       2     120
3       3     120
4       4     120
5       5     112
6       6     112
7       7     120
8       8     120
9       9     120
10     10     120
11     11     120
12     12     120
13     13     120
14     14     120
15     15     120
16     16     120
17     17     112
18     18     120
19     19     112
20     20     120
21     21     120
22     22     120
23     23     120
24     24     120
25     25     120
26     26     120
27     27     112
28     28     120
29     29     120
30     30     120
31     31     120
32     32     120
33     33     120
34     34     120
35     35     120
36     36     120
37     37     120
38     38     120
39     39     120
40     40     120
41     41     120
42     42     120
43     43     120
44     44     120
45     45     120
46     46     120
47     47     120
48     48     120
49     49     120
50     50     120
51     51     120
52     52     120
53     53     120
54     54     112
55     55     120
56     56     120
57     57     120
58     58     120
59     59     120

In [61]:
aux_df[aux_df['id_simulation'] == 'sim_alt_600_raan_170']

           id_simulation  srcId  counts
0   sim_alt_600_raan_170      0       9
1   sim_alt_600_raan_170      1       9
2   sim_alt_600_raan_170      2       9
3   sim_alt_600_raan_170      3       9
4   sim_alt_600_raan_170      4       9
5   sim_alt_600_raan_170      5       8
6   sim_alt_600_raan_170      6       8
7   sim_alt_600_raan_170      7       9
8   sim_alt_600_raan_170      8       9
9   sim_alt_600_raan_170      9       9
10  sim_alt_600_raan_170     10       9
11  sim_alt_600_raan_170     11       9
12  sim_alt_600_raan_170     12       9
13  sim_alt_600_raan_170     13       9
14  sim_alt_600_raan_170     14       9
15  sim_alt_600_raan_170     15       9
16  sim_alt_600_raan_170     16       9
17  sim_alt_600_raan_170     17       8
18  sim_alt_600_raan_170     18       9
19  sim_alt_600_raan_170     19       8
20  sim_alt_600_raan_170     20       9
21  sim_alt_600_raan_170     21       9
22  sim_alt_600_raan_170     22       9
23  sim_alt_600_raan_170     23       9
24  sim_alt_600_raan_170     24       9
25  sim_alt_600_raan_170     25       9
26  sim_alt_600_raan_170     26       9
27  sim_alt_600_raan_170     27       8
28  sim_alt_600_raan_170     28       9
29  sim_alt_600_raan_170     29       9
30  sim_alt_600_raan_170     30       9
31  sim_alt_600_raan_170     31       9
32  sim_alt_600_raan_170     32       9
33  sim_alt_600_raan_170     33       9
34  sim_alt_600_raan_170     34       9
35  sim_alt_600_raan_170     35       9
36  sim_alt_600_raan_170     36       9
37  sim_alt_600_raan_170     37       9
38  sim_alt_600_raan_170     38       9
39  sim_alt_600_raan_170     39       9
40  sim_alt_600_raan_170     40       9
41  sim_alt_600_raan_170     41       9
42  sim_alt_600_raan_170     42       9
43  sim_alt_600_raan_170     43       9
44  sim_alt_600_raan_170     44       9
45  sim_alt_600_raan_170     45       9
46  sim_alt_600_raan_170     46       9
47  sim_alt_600_raan_170     47       9
48  sim_alt_600_raan_170     48       9
49  sim_alt_600_raan_170     49       9
50  sim_alt_600_raan_170     50       9
51  sim_alt_600_raan_170     51       9
52  sim_alt_600_raan_170     52       9
53  sim_alt_600_raan_170     53       9
54  sim_alt_600_raan_170     54       8
55  sim_alt_600_raan_170     55       9
56  sim_alt_600_raan_170     56       9
57  sim_alt_600_raan_170     57       9
58  sim_alt_600_raan_170     58       9
59  sim_alt_600_raan_170     59       9